---
name: Yueguang Wang
version: 2.10.2
slug: yueguang_wang
description: Moonlight Web Stream packaged as a Home Assistant app.
url: https://github.com/LEGION-IS-MY-NAME/YueguangWang
arch:
  - amd64
  - aarch64
startup: application
boot: manual
init: false
host_network: true
ingress: true
ingress_port: 8080
ingress_stream: true
panel_icon: mdi:moon-waning-crescent
panel_title: Yueguang Wang
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Moonlight Web interface
map:
  - addon_config:rw
options:
  webrtc_port_range: "40000:40100"
  webrtc_nat_1to1_host: ""
  log_level: "info"
  path_prefix: ""
schema:
  bind_address: str?
  webrtc_port_range: str
  webrtc_nat_1to1_host: str?
  log_level: list(trace|debug|info|warn|error|off)
  path_prefix: str?
watchdog: "tcp://[HOST]:[PORT:8080]"
